# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/INS_RAM/INS_RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==INS_RAM || ORIG_REF_NAME==INS_RAM} -quiet] -quiet

# IP: ip/BRAM64_1024_1/BRAM64_1024.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM64_1024 || ORIG_REF_NAME==BRAM64_1024} -quiet] -quiet

# Block Designs: bd/cryptoprocessor/cryptoprocessor.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cryptoprocessor || ORIG_REF_NAME==cryptoprocessor} -quiet] -quiet

# IP: bd/cryptoprocessor/ip/cryptoprocessor_processing_system7_0_0/cryptoprocessor_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cryptoprocessor_processing_system7_0_0 || ORIG_REF_NAME==cryptoprocessor_processing_system7_0_0} -quiet] -quiet

# IP: bd/cryptoprocessor/ip/cryptoprocessor_AXI_Slave8Ports_new_0_0/cryptoprocessor_AXI_Slave8Ports_new_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cryptoprocessor_AXI_Slave8Ports_new_0_0 || ORIG_REF_NAME==cryptoprocessor_AXI_Slave8Ports_new_0_0} -quiet] -quiet

# IP: bd/cryptoprocessor/ip/cryptoprocessor_ps7_0_axi_periph_0/cryptoprocessor_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cryptoprocessor_ps7_0_axi_periph_0 || ORIG_REF_NAME==cryptoprocessor_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/cryptoprocessor/ip/cryptoprocessor_rst_ps7_0_100M_0/cryptoprocessor_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cryptoprocessor_rst_ps7_0_100M_0 || ORIG_REF_NAME==cryptoprocessor_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/cryptoprocessor/ip/cryptoprocessor_ComputeCoreWrapper_0_0/cryptoprocessor_ComputeCoreWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cryptoprocessor_ComputeCoreWrapper_0_0 || ORIG_REF_NAME==cryptoprocessor_ComputeCoreWrapper_0_0} -quiet] -quiet

# IP: ip/INS_RAM/INS_RAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==INS_RAM || ORIG_REF_NAME==INS_RAM} -quiet] -quiet

# IP: ip/BRAM64_1024_1/BRAM64_1024.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM64_1024 || ORIG_REF_NAME==BRAM64_1024} -quiet] -quiet

# IP: bd/cryptoprocessor/ip/cryptoprocessor_auto_pc_0/cryptoprocessor_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cryptoprocessor_auto_pc_0 || ORIG_REF_NAME==cryptoprocessor_auto_pc_0} -quiet] -quiet

# XDC: ip/INS_RAM/INS_RAM_ooc.xdc

# XDC: ip/BRAM64_1024_1/BRAM64_1024_ooc.xdc

# XDC: ip/INS_RAM/INS_RAM_ooc.xdc

# XDC: ip/BRAM64_1024_1/BRAM64_1024_ooc.xdc

# XDC: bd/cryptoprocessor/cryptoprocessor_ooc.xdc
