set_property SRC_FILE_INFO {cfile:/home/florian/Desktop/proteus/ntt_op_3_4/project_1/project_1.srcs/constrs_1/new/constraints.xdc rfile:../../../project_1.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {cryptoprocessor_i/ComputeCoreWrapper_0/inst/CORE/RNG/TRO/*/*}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {cryptoprocessor_i/ComputeCoreWrapper_0/inst/CORE/RNG/TRO/*/*/*}]
